export const THEME_COLOR_CLASS_TYPE_CLASS = `#1bade5`;
export const THEME_COLOR_CLASS_TYPE_LIVE = `#0e78d5`;
export const THEME_COLOR_CLASS_TYPE_STUDY = `#13aaa9`;
export const THEME_COLOR_CLASS_TYPE_TASK = `#afba0a`;
export const WIDGET_SCHEDULE_ORIENTATION_SWITCH_WIDTH = 740;
