query getStudentNameById($filter: UserFilter) {
  usersConnection(filter: $filter, direction: FORWARD) {
    edges {
      node {
        id
        givenName
        familyName
      }
    }
  }
}
query classesTeachersConnection(
  $cursor: String,
  $filter: ClassFilter,
  $teacherFilter: UserFilter,
  $teacherCursor: String,
  ) {
classesConnection(
    filter: $filter
    directionArgs: {
    cursor: $cursor
    },
    direction: FORWARD
    sort:{
    order:ASC
    field:name
    }
    ) {
     totalCount
     edges {
      node {
        id
        name
        teachersConnection(filter: $teacherFilter, cursor: $teacherCursor, direction: FORWARD) {
          totalCount
          edges {
            cursor
            node {
              id
              givenName
              familyName
              status
            }
          }
          pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
          }
        },
      }
    }
    pageInfo{
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor

    }
  }
}
query classNode($classId:ID!,$teacherCursor:String){
  classNode(id:$classId){
    name
    teachersConnection(cursor:$teacherCursor){
      totalCount
      edges{
        node{
          id
          familyName
          givenName
          status
        }
      }
      pageInfo{
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      }
      
    }
  }

}
# schools | classes 1
query classesBySchoolId (
  $cursor: String,
  $filter: ClassFilter,
  $schoolId:ID!,
  ) {
  schoolNode(id:$schoolId){
    organizationId
    classesConnection(filter: $filter,
      cursor: $cursor
      direction: FORWARD
     ){
      totalCount
      pageInfo{
        endCursor
        hasNextPage
      }
      edges{
        node{
          id
          name
        }
      }
    }
  }
  }
# schools | classes 2
query classesList(
  $cursor: String,
  $filter: ClassFilter,
  ) {
classesConnection(
    filter: $filter,
    directionArgs: {
    cursor: $cursor
    },
    direction: FORWARD
  ) {
    totalCount
     edges {
      node {
        id
        name
      }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
  # schools | classes 3
  query schoolsClasses (
  $cursor: String,
  $filter: SchoolFilter,
  ) {
schoolsConnection(
    filter: $filter,
    directionArgs: {
    cursor: $cursor
    },
    direction: FORWARD
    sort:{
    order:ASC
    field:name
    }
  ) {
    totalCount
     edges {
      node {
        id
        name
        classesConnection( direction: FORWARD) {
          totalCount
           edges {
            node {
              id
              name
            }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
        }
      }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }