query teachersByOrgnization($organization_id: ID = "3f135b91-a616-4c80-914a-e4463104dbac") {
  organization(organization_id: $organization_id) {
    teachers {
      user {
        user_id
        user_name
      }
    }
  }
}

query classesByTeacher($user_id: ID = "7d0ad09a-11ab-4147-9734-974276f397d1") {
  user(user_id: $user_id) {
    classesTeaching {
      class_id
      class_name
    }
  }
}

query classesByOrganization($organization_id: ID = "3f135b91-a616-4c80-914a-e4463104dbac") {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      class_name
    }
  }
}

query participantsByClass($class_id: ID = "c479bd4b-faf8-4a4b-80b6-632c3234d804") {
  class(class_id: $class_id) {
    teachers {
      user_id
      user_name
    }
    students {
      user_id
      user_name
    }
  }
}

query qeuryPermissionOfMe($organization_id: ID! = "3f135b91-a616-4c80-914a-e4463104dbac") {
  me {
    membership(organization_id: $organization_id) {
      roles {
        permissions {
          permission_name
        }
      }
    }
  }
}