query roleBasedUsersByOrgnization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    roles {
      role_name
      memberships {
        user {
          user_id
          user_name
        }
      }
    }
  }
}

query teachersByOrgnization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    teachers {
      user {
        user_id
        user_name
      }
    }
  }
}

query classesByTeacher($user_id: ID!) {
  user(user_id: $user_id) {
    classesTeaching {
      class_id
      class_name
    }
  }
}

query classesByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      class_name
      status
      schools {
        school_id
        school_name
      }
      teachers {
        user_id
        user_name
      }
      students {
        user_id
        user_name
      }
    }
  }
}

query classesSchoolsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      ...classIdName
      schools {
        school_id
      }
    }
  }
}

query classesTeachersByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      teachers {
        ...userIdName
        school_memberships {
          school_id
        }
      }
    }
  }
}


query classStudentsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      students{
        user_id
        full_name
      }
    }
  }
}

query schoolsIdNameByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    schools {
      school_id
      school_name
    }
  }
}
query schoolsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      class_name
      schools {
        school_id
      }
    }
    schools {
      school_id
      school_name
      classes {
        ...classIdName
      }
    }
  }
}

query participantsByClass($class_id: ID!) {
  class(class_id: $class_id) {
    teachers {
      ...userIdName
    }
    students {
      ...userIdName
    }
  }
}

query qeuryMe($organization_id: ID!) {
  me {
    ...userIdName
    membership(organization_id: $organization_id) {
      roles {
        permissions {
          permission_name
        }
      }
    }
  }
}


query myPermissionsAndClassesTeachingQuery($organization_id: ID!) {
  me {
    user_id
    membership(organization_id: $organization_id) {
      organization_id
      schoolMemberships {
        school_id
      }
      classesTeaching {
        class_id
      }
    }
  }
}

query getStudentNameById($filter: UserFilter) {
  usersConnection(filter: $filter, direction: FORWARD) {
    edges {
      node {
        id
        givenName
        familyName
      }
    }
  }
}

query organizations {
  organizations {
    organization_id
    organization_name
  }
}

query getSchoolTeacher($user_id: ID!) {
  user(user_id: $user_id) {
    school_memberships {
      school {
        status
        school_id
        school_name
        organization {
          organization_id
        }
        classes {
          status
          teachers {
            ...userIdName
          }
        }
      }
    }
  }
}

query teacherByOrgId($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      status
      ...classIdName
      teachers {
        ...userIdName
        school_memberships {
          school_id
        }
      }
    }
  }
}

query mySchoolIDs($organization_id: ID!) {
  me {
    membership(organization_id: $organization_id) {
      schoolMemberships {
        school_id
      }
    }
  }
}

query classesBySchool($school_id: ID!) {
  school(school_id: $school_id) {
    classes {
      ...classIdName
      status
      schools {
        school_id
        school_name
      }
      teachers {
        ...userIdName
      }
      students {
        ...userIdName
      }
    }
  }
}

query userSchoolIDs($user_id: ID!) {
  user(user_id: $user_id) {
    school_memberships {
      school_id
    }
  }
}

query participantsBySchool($school_id: ID!) {
  school(school_id: $school_id) {
    classes {
      status
      teachers {
        user_id
        user_name
        school_memberships {
          school_id
        }
      }
      students {
        user_id
        user_name
        school_memberships {
          school_id
        }
      }
    }
  }
}

query participantsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    status
    classes {
      teachers {
        user_id
        user_name
        school_memberships {
          school_id
          school {
            organization {
              organization_id
            }
          }
        }
      }
      students {
        user_id
        user_name
        school_memberships {
          school_id
        }
      }
    }
  }
}

query classesTeachingQuery($user_id: ID!, $organization_id: ID!) {
  user(user_id: $user_id) {
    membership(organization_id: $organization_id) {
      classesTeaching {
        class_id
        class_name
        status
        schools {
          school_id
          school_name
        }
        teachers {
          user_id
          user_name
        }
        students {
          user_id
          user_name
        }
      }
    }
  }
}

query classesStudentQuery($user_id: ID!, $organization_id: ID!) {
  user(user_id: $user_id) {
    membership(organization_id: $organization_id) {
      classes {
        class_id
        class_name
        status
        schools {
          school_id
          school_name
        }
        teachers {
          user_id
          user_name
        }
        students {
          user_id
          user_name
        }
      }
    }
  }
}

query schoolByUserQuery($user_id: ID!, $organization_id: ID!) {
  user(user_id: $user_id) {
    membership(organization_id: $organization_id) {
      schoolMemberships {
        school {
          school_id
          school_name
          classes {
            status
            class_id
            class_name
            teachers {
              user_id
              user_name
            }
            students {
              user_id
              user_name
            }
          }
        }
      }
    }
  }
}

query schoolByOrgQuery($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    schools {
      school_id
      school_name
      classes {
        status
        class_id
        class_name
        teachers {
          user_id
          user_name
        }
        students {
          user_id
          user_name
        }
      }
    }
  }
}
query teacherListBySchoolId($school_id: ID!) {
  school(school_id: $school_id) {
    classes {
      status
      class_id
      teachers {
        user_id
        user_name
      }
    }
  }
}
query notParticipantsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      status
      schools {
        school_id
        school_name
      }
      teachers {
        user_id
        user_name
        school_memberships {
          school_id
          school {
            school_name
            organization {
              organization_id
            }
          }
        }
      }
    }
  }
}

query schoolAndTeacherByOrg($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    schools {
      school_id
      school_name
      status
      classes {
        status
        class_id
        class_name
        teachers {
          user_id
          user_name
        }
      }
    }
  }
}

query getPrograms($program_id: ID!) {
  program(id: $program_id) {
    id
    name
    status
    subjects {
      id
      name
      status
      categories {
        id
        name
        status
        subcategories {
          id
          name
          status
        }
      }
    }
    age_ranges {
      id
      name
      status
    }
    grades {
      id
      name
      status
    }
  }
}
query studentsByOrganization($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    classes {
      class_id
      class_name
      schools {
        school_id
      }
      students {
        user_id
        user_name
      }
    }
    schools {
      school_id
      school_name
      classes {
        class_id
        class_name
        students {
          user_id
          user_name
        }
      }
    }
  }
}

query getSubjects($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    subjects {
      id
      name
    }
  }
}

query getProgramsAndSubjects($organization_id: ID!) {
  organization(organization_id: $organization_id) {
    programs {
      id
      name
      subjects {
        id
        name
      }
    }
  }
}

query getSchoolsFilterList($filter: SchoolFilter, $direction: ConnectionDirection!, $directionArgs: ConnectionsDirectionArgs){
  schoolsConnection(filter: $filter, direction:$direction, directionArgs: $directionArgs) {
     totalCount
     edges{
      cursor
      node {
        id
        name
      }
    }
    pageInfo {
      hasNextPage
    }
  }
}

query getClassFilterList($filter: ClassFilter, $direction: ConnectionDirection!, $directionArgs: ConnectionsDirectionArgs){
  classesConnection(filter: $filter, direction: $direction, directionArgs: $directionArgs) {
     totalCount
     edges {
      cursor
      node {
        id
        name
      }
    }
     pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}

query getUser($filter: UserFilter, $direction: ConnectionDirection!) {
  usersConnection(
    direction: $direction,
    filter: $filter
  ) {
    edges {
      node {
        id
        givenName
        familyName
        status
        roles {
          id
          name
        }
      }
    }
  }
}


fragment userIdName on User {
  user_id
  user_name
}

fragment classIdName on Class {
  class_id
  class_name
}