name: container builds

concurrency:
  group: LandingZoneDeployment
  cancel-in-progress: true

on:
  # Triggers the workflow when there's a release published
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Repository specific variables
env:
  ecr_repository: kidsloop-schedule-frontend
  argocd_app_chart_tag_path: scheduleFrontend.tag
  argocd_app_component: schedule-frontend

jobs:
  install:
    uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v1.1.5
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

  build-container:
    needs: [install]
    strategy:
      matrix:
        include:
          - environment: landingzone
            region: uk
          - environment: prod
            region: uk
          - environment: beta
            region: id
          - environment: prod
            region: id
          - environment: prod
            region: th
          - environment: beta
            region: vn
          - environment: prod
            region: vn
          - environment: alpha
            region: vn
          - environment: prod
            region: in
          - environment: prod
            region: lk
          - environment: uat
            region: mb
          - environment: prod
            region: pk
          - environment: prod
            region: global
          - environment: alpha
            region: global
          - environment: loadtest
            region: global
          - environment: nextgen
            region: global
          - environment: showroom
            region: global
          - environment: stage
            region: global
    name: build container
    runs-on: ubuntu-latest
    env:
      region: ${{ matrix.region }}
      environment: ${{ matrix.environment }}
    steps:
      - uses: KL-Engineering/github-action-workflows/.github/actions/npm-build-fe@d51babc87eeba745b2ceaf8aa51b9381dec9f71e
        with:
          environment: ${{ env.environment }}
          region: ${{ env.region }}
      - name: Add compiled files to the container deploy directory
        run: cp -r dist deploy/

      - name: Build and Push Container
        uses: KL-Engineering/github-action-workflows/.github/actions/docker-build-push@d51babc87eeba745b2ceaf8aa51b9381dec9f71e
        with:
          environment: ${{ env.environment }}
          region: ${{ env.region }}
          ecr_repository: ${{ env.ecr_repository }}
          ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}

  deploy-ci:
    needs: [build-container]
    strategy:
      matrix:
        include:
          - environment: landingzone
            url: https://schedule.landing-zone.kidsloop.live
            region: uk
    environment:
      url: ${{ matrix.url }}
      name: ${{ matrix.environment }}
    name: deploy
    runs-on: ubuntu-latest
    env:
      region: ${{ matrix.region }}
      environment: ${{ matrix.environment }}
    steps:
      - name: Deploy to ${{ matrix.environment }}
        uses: KL-Engineering/github-action-workflows/.github/actions/argocd-override-image-parameter@d51babc87eeba745b2ceaf8aa51b9381dec9f71e
        with:
          environment: ${{ env.environment }}
          region: ${{ env.region }}
          argocd_app: "${{ env.region }}-${{ env.environment }}-${{ env.argocd_app_component }}"
          argocd_app_chart_tag_path: ${{ env.argocd_app_chart_tag_path }}
          TOOLS_KUBECONFIG_CONTENT_B64: ${{ secrets.TOOLS_KUBECONFIG_CONTENT_B64 }}
          ARGOCD_AUTH_USERNAME: ${{ secrets.ARGOCD_AUTH_USERNAME }}
          ARGOCD_AUTH_PASSWORD: ${{ secrets.ARGOCD_AUTH_PASSWORD }}
